# Generated by Django 2.1.7 on 2019-06-21 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190621_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 21, 8, 24, 58, 888131, tzinfo=utc)),
        ),
    ]
